// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://slmnxumrowxbpuxqbttx.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InNsbW54dW1yb3d4YnB1eHFidHR4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjE3ODY2ODYsImV4cCI6MjA3NzM2MjY4Nn0.U31fXrRCQxnOBF_42GITVrNdXZKjC221MtzxvpzNVVY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});